-- MySQL Script generated by MySQL Workbench
-- jue 14 may 2020 12:08:57 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_id`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_id` (
  `idTipo_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`semestre` (
  `idSemestre` INT NOT NULL AUTO_INCREMENT,
  `periodo` VARCHAR(45) NULL,
  `anio` VARCHAR(45) NULL,
  PRIMARY KEY (`idSemestre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materia` (
  `idMateria` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `Semestre_idSemestre` INT NOT NULL,
  PRIMARY KEY (`idMateria`),
  INDEX `fk_Materia_Semestre1_idx` (`Semestre_idSemestre`  )  ,
  CONSTRAINT `fk_Materia_Semestre1`
    FOREIGN KEY (`Semestre_idSemestre`)
    REFERENCES `mydb`.`semestre` (`idSemestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genero` (
  `idGenero` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `id_Persona` INT NOT NULL,
  `Genero_idGenero` INT NOT NULL,
  `Tipo_id_idTipo_id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NOT NULL,
  `correo_contacto` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NULL,
  PRIMARY KEY (`id_Persona`),
  INDEX `fk_Persona_Genero1_idx` (`Genero_idGenero`  )  ,
  INDEX `fk_Persona_Tipo_id1_idx` (`Tipo_id_idTipo_id`  )  ,
  CONSTRAINT `fk_Persona_Genero1`
    FOREIGN KEY (`Genero_idGenero`)
    REFERENCES `mydb`.`genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Tipo_id1`
    FOREIGN KEY (`Tipo_id_idTipo_id`)
    REFERENCES `mydb`.`tipo_id` (`idTipo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profesor` (
  `Persona_id_Persona` INT NOT NULL,
  `codigo_profesor` VARCHAR(45) NULL,
  PRIMARY KEY (`Persona_id_Persona`),
  UNIQUE INDEX `codigo_profesor_UNIQUE` (`codigo_profesor`  )  ,
  CONSTRAINT `fk_Profesor_Persona1`
    FOREIGN KEY (`Persona_id_Persona`)
    REFERENCES `mydb`.`persona` (`id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grupo` (
  `idGrupo` INT NOT NULL,
  `Materia_idMateria` INT NOT NULL,
  `Profesor_Persona_id_Persona` INT NOT NULL,
  PRIMARY KEY (`idGrupo`),
  INDEX `fk_Grupo_Materia1_idx` (`Materia_idMateria`  )  ,
  INDEX `fk_Grupo_Profesor1_idx` (`Profesor_Persona_id_Persona`  )  ,
  CONSTRAINT `fk_Grupo_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `mydb`.`materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_Profesor1`
    FOREIGN KEY (`Profesor_Persona_id_Persona`)
    REFERENCES `mydb`.`profesor` (`Persona_id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administrador` (
  `fecha_entrada` DATE NULL,
  `fecha_salida` VARCHAR(45) NULL,
  `Profesor_Persona_id_Persona` INT NOT NULL,
  PRIMARY KEY (`Profesor_Persona_id_Persona`),
  CONSTRAINT `fk_Administrador_Profesor1`
    FOREIGN KEY (`Profesor_Persona_id_Persona`)
    REFERENCES `mydb`.`profesor` (`Persona_id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`visita` (
  `idVisita` INT NOT NULL AUTO_INCREMENT,
  `fecha_visita_inicio` DATE NULL,
  `grupo_id` VARCHAR(45) NULL,
  `Grupo_idGrupo` INT NOT NULL,
  `Administrador_Profesor_Persona_id_Persona` INT NOT NULL,
  `fecha_visita_salida` DATE NULL,
  `duracion` VARCHAR(45) NULL,
  `cupos_disponibles` VARCHAR(45) NULL,
  PRIMARY KEY (`idVisita`),
  INDEX `fk_Visita_Grupo1_idx` (`Grupo_idGrupo`  )  ,
  INDEX `fk_Visita_Administrador1_idx` (`Administrador_Profesor_Persona_id_Persona`  )  ,
  CONSTRAINT `fk_Visita_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `mydb`.`grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visita_Administrador1`
    FOREIGN KEY (`Administrador_Profesor_Persona_id_Persona`)
    REFERENCES `mydb`.`administrador` (`Profesor_Persona_id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudiante` (
  `Persona_id_Persona` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  PRIMARY KEY (`Persona_id_Persona`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo`  )  ,
  CONSTRAINT `fk_Estudiante_Persona1`
    FOREIGN KEY (`Persona_id_Persona`)
    REFERENCES `mydb`.`persona` (`id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`asistencia` (
  `idAsistencia` INT NOT NULL AUTO_INCREMENT,
  `aprobado` TINYINT NULL,
  `fecha_registro` DATE NULL,
  `Visita_idVisita` INT NOT NULL,
  `Estudiante_Persona_id_Persona` INT NOT NULL,
  `Estudiante_Persona_Tipo_id_idTipo_id` INT NOT NULL,
  PRIMARY KEY (`idAsistencia`),
  INDEX `fk_Asistencia_Visita1_idx` (`Visita_idVisita`  )  ,
  INDEX `fk_Asistencia_Estudiante1_idx` (`Estudiante_Persona_id_Persona`  , `Estudiante_Persona_Tipo_id_idTipo_id`  )  ,
  CONSTRAINT `fk_Asistencia_Visita1`
    FOREIGN KEY (`Visita_idVisita`)
    REFERENCES `mydb`.`visita` (`idVisita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asistencia_Estudiante1`
    FOREIGN KEY (`Estudiante_Persona_id_Persona`)
    REFERENCES `mydb`.`estudiante` (`Persona_id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresa` (
  `rut` INT NOT NULL,
  `nombre_razon_social` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(100) NULL,
  `representante_legal` INT NOT NULL,
  PRIMARY KEY (`rut`),
  INDEX `fk_Empresa_Persona1_idx` (`representante_legal`  )  ,
  CONSTRAINT `fk_Empresa_Persona1`
    FOREIGN KEY (`representante_legal`)
    REFERENCES `mydb`.`persona` (`id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `idTipo_usuario` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `Tipo_usuario_idTipo_usuario` INT NOT NULL,
  `correo_usuario` VARCHAR(45) NULL,
  `contrasena` VARCHAR(255) NULL,
  `verificado` TINYINT NULL,
  `id_usuario` INT NOT NULL,
  INDEX `fk_Usuario_Tipo_usuario1_idx` (`Tipo_usuario_idTipo_usuario`  )  ,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_persona1_idx` (`id_usuario`  )  ,
  CONSTRAINT `fk_Usuario_Tipo_usuario1`
    FOREIGN KEY (`Tipo_usuario_idTipo_usuario`)
    REFERENCES `mydb`.`tipo_usuario` (`idTipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`persona` (`id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_doc_apoyo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_doc_apoyo` (
  `idTipo_doc_Apoyo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(300) NULL,
  PRIMARY KEY (`idTipo_doc_Apoyo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`documento_apoyo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documento_apoyo` (
  `Tipo_doc_Apoyo_idTipo_doc_Apoyo` INT NOT NULL,
  `id_doc` INT NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `direccion_url` VARCHAR(300) NULL,
  `fecha_creacion` VARCHAR(45) NULL,
  `Visita_idVisita` INT NOT NULL,
  INDEX `fk_Documento_Apoyo_Tipo_doc_Apoyo1_idx` (`Tipo_doc_Apoyo_idTipo_doc_Apoyo`  )  ,
  PRIMARY KEY (`id_doc`),
  INDEX `fk_Documento_Apoyo_Visita1_idx` (`Visita_idVisita`  )  ,
  CONSTRAINT `fk_Documento_Apoyo_Tipo_doc_Apoyo1`
    FOREIGN KEY (`Tipo_doc_Apoyo_idTipo_doc_Apoyo`)
    REFERENCES `mydb`.`tipo_doc_apoyo` (`idTipo_doc_Apoyo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Documento_Apoyo_Visita1`
    FOREIGN KEY (`Visita_idVisita`)
    REFERENCES `mydb`.`visita` (`idVisita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
